# Air Configuration File

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
include_dir = [
    "internal/api/auth",
    "internal/api/course",
    "internal/api/job",
    "internal/api/mentorship",
    "internal/api/test",
    "internal/api/user",
    "internal/config",
    "internal/core/course",
    "internal/core/job",
    "internal/core/mentorship",
    "internal/core/test",
    "internal/core/user",
    "internal/database",
    "internal/lib",
    "internal/middleware",
    "internal/types",
    "internal/utils",
    "pkg",
]
include_ext = ["go", "tpl", "tmpl", "html", "env"]
args_bin = []
bin = "tmp/main.exe"
cmd = "go build -o ./tmp/main.exe ./main.go"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_file = ["*.go", ".env"]
kill_delay = "0s"
log = "tmp/build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"
